# Install TalosCTL on Ansible node
- name: Install TalosCTL
  hosts: ansible
  gather_facts: true
  become: true
  roles:
    - install-talosctl

# Configure Cluster Configuration
- name: Configure Cluster
  hosts: ansible
  gather_facts: true
  roles:
    - configure-cluster

# Apply Cluster Configuration
- name: Configure Cluster
  hosts: ansible
  gather_facts: true
  roles:
    - apply-config

# Configure TalosCTL
- name: Configure TalosCTL
  hosts: ansible
  gather_facts: true
  roles:
    - configure-talosctl

# Add Workers
- name: Add Workers
  hosts: ansible
  gather_facts: true
  roles:
    - add-workers