---
# Ansible Playbook to install Talos
- name: Download talosctl for Linux (amd64)
  ansible.builtin.get_url:
    url: https://github.com/siderolabs/talos/releases/download/{{ talosctl_version }}/talosctl-linux-amd64
    dest: /usr/local/bin/talosctl
    mode: '0755'  
  register: download_result

- name: Display download result
  ansible.builtin.debug:
    var: download_result