---
# Generate Machine Configurations.
- name: Apply config to first worker
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure --nodes {{ worker_1 }} --file {{ config_directory }}/worker.yaml
  changed_when: true