os: "linux"
arch: "amd64"

talos_version: v1.7.0
talosctl_version: v1.7.5
control_plane_ip: 192.168.76.21

worker_1: 192.168.76.22
worker_2: 192.168.76.23

config_directory: "/home/{{ ansible_user }}/.talos"
config_file: "/home/{{ ansible_user }}/.talos/talosconfig"

kube_vip_version: "v0.8.0"
vip_interface: eth0
vip: 192.168.5.50

# metallb_version: v0.13.12
# lb_range: 192.168.76.80-192.168.76.90
# lb_pool_name: first-pool

ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo